version: '3'
services:
  webservice:
    image: 'registry.iop-ventures.com/tresor/tools-sdk-service/app:rc'
    container_name: webservice
    networks:
      - core
    environment:
      - hydraledgerNetwork=devnet
    ports:
      - 4201:4201

networks:
  core:
